stages:
- name: build
  steps:
  - runScriptConfig:
      image: golang:1.11
      shellScript: "ls \ngo build -o test  test.go\nls"
- name: dockerfile
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: gotest:${CICD_EXECUTION_SEQUENCE}
      registry: 127.0.0.1:34887
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
